export const store = {
  dogs: [
    {
      name: "Bosse",
      breed: "Husky",
      gender: "Male",
      genderIcon: "/assets/Vectormale.svg",
      age: 4,
      owner: "Pelle Stöök",
      present: true,
      img: "/assets/Bosse.png",
    },
    {
      name: "Lola",
      breed: "Purebred puppy",
      gender: "Female",
      genderIcon: "/assets/Vectorfemale.svg",
      age: 2,
      owner: "Sandra Lolita",
      present: true,
      img: "/assets/Lola.png",
    },
    {
      name: "Fido",
      breed: "Tax",
      gender: "Male",
      genderIcon: "/assets/Vectormale.svg",
      age: 1,
      owner: "Goran Acki",
      present: false,
      img: "/assets/Fido.png",
    },
    {
      name: "Selma",
      breed: "Labrador",
      gender: "Female",
      genderIcon: "/assets/Vectorfemale.svg",
      age: 10,
      owner: "Pelle Bruul",
      present: false,
      img: "/assets/Selma.png",
    },
  ],
};
